// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using blog_template_practice;

namespace BlogPlatform.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20210309015338_SeedComments")]
    partial class SeedComments
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("blog_template_practice.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "You know, it's that stuff you eat! People grow stuff, raise livestock, gather fruits and whatnot... then other people market and sell it, you buy it, cook it and then shove it down your mouth-hole. Or eat it raw. Whatever, it's you're body. You know, you are what you eat, so it's basically you.",
                            Name = "Food"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Modern technology has led to incredible feats of engineering that allow us to experience crazy adventures all from our own homes in the form of video games. Whether puzzles, shooters, adventures, sports, you can do pretty much anything with video games. What will they think of next?",
                            Name = "Video Games"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The moving pictures, they were once called. Movies take us on incredible fantastic adventures and let us explore the human psyche through watching beautiful people perfom amazing stories all for our amusement.",
                            Name = "Movies"
                        });
                });

            modelBuilder.Entity("blog_template_practice.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "sandwich_purist4779",
                            Body = "Hot dogs are NOT sandwiches!!!! Why do people keep saying they are?",
                            ContentId = 1,
                            PostDate = new DateTime(2021, 3, 8, 20, 53, 37, 461, DateTimeKind.Local).AddTicks(4379)
                        },
                        new
                        {
                            Id = 2,
                            Author = "MrStrange",
                            Body = "Okay, this is clearly talking about WandaVision, and that's not even a movie. This dude is whack",
                            ContentId = 2,
                            PostDate = new DateTime(2021, 3, 8, 20, 53, 37, 462, DateTimeKind.Local).AddTicks(1125)
                        },
                        new
                        {
                            Id = 3,
                            Author = "kirbymain",
                            Body = "Ugh, seriously???? We only need one Fire Emblem character. Puke",
                            ContentId = 3,
                            PostDate = new DateTime(2021, 3, 8, 20, 53, 37, 462, DateTimeKind.Local).AddTicks(1305)
                        });
                });

            modelBuilder.Entity("blog_template_practice.Models.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublishDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Contents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "hotdogluvr_and_chipfnatic",
                            Body = "There's bread, and meat in between. What more do you need?!?!?!?!? Get some mustard in there, maybe ketchup if you're frisky, relish or chili, c'mon! Fuhgeddaboutit!!!!",
                            CategoryId = 1,
                            PostDate = new DateTime(2021, 3, 8, 20, 53, 37, 461, DateTimeKind.Local).AddTicks(1866),
                            PublishDate = "03/05/21",
                            Title = "Hotdogs are definitely sandwiches."
                        },
                        new
                        {
                            Id = 2,
                            Author = "elderlycurmudgeon",
                            Body = "Oh the kids these days with their confounded superheroes. Everyone always says \"Oh this one is different, it's new and better than all the others\" but it's not! There's always the implausible origin story, with a tortured too-long build to make them into the superhero we all know they are, and then once you get past that, you have to know who everyone else in the movie is. Who's that robot guy? Why does he live with the redhead? I don't have time to watch all these movies with how many times I mow my lawn. I need something that explains everything all the time. Maybe there should be more subtitles on everything.",
                            CategoryId = 2,
                            PostDate = new DateTime(2021, 3, 8, 20, 53, 37, 461, DateTimeKind.Local).AddTicks(2105),
                            PublishDate = "03/05/21",
                            Title = "Marvel movies are overrated"
                        },
                        new
                        {
                            Id = 3,
                            Author = "imaimaima_marthboy",
                            Body = "While there are many FE characters in SSBU, the inclusion of all of them is justified. While some are similar, their differences are great enough to warrant separate characters. I won't go into specifics, but we need them all to maintain competitive play. If they do another after Byleth though, that will be too many. Also, instead of Byleth they should have included Claude in order to have an entirely upside-down character or Flayn so that they could have added a fishing mini-game.",
                            CategoryId = 3,
                            PostDate = new DateTime(2021, 3, 8, 20, 53, 37, 461, DateTimeKind.Local).AddTicks(2119),
                            PublishDate = "03/05/21",
                            Title = "There are not too many Fire Emblem characters in Smash Bros. Ultimate"
                        });
                });

            modelBuilder.Entity("blog_template_practice.Models.Comment", b =>
                {
                    b.HasOne("blog_template_practice.Models.Content", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("blog_template_practice.Models.Content", b =>
                {
                    b.HasOne("blog_template_practice.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
